version: "3"

services:
  temper_exporter:
    build: ./temper_exporter
    container_name: temper_exporter
    restart: unless-stopped
    ports:
      - "9897:9897"
    logging:
      options:
        max-size: 10m
    networks:
      - v1-network

networks:
  v1-network:
    external: true
